### ISSUE TITLE
InstaVPN do the same ;)

### ISSUE THREAD

**Issue by dimzon** [philplckthun/setup-simple-ipsec-l2tp-vpn#10]
https://github.com/sockeye44/instavpn

**Comment by philplckthun** [comment]
This is not a convenience layer for users, this is just a lightweight installation script. It's totally different in what it does to InstaVPN. The result is probably comparable, and InstaVPN supports further administration, but if you want to get a fully configured IPSec/L2TP VPN running quickly and easily, this is the way to go.
