### ISSUE TITLE
ipsec-assist: unrecognized service

### ISSUE THREAD

**Issue by tom95588** [philplckthun/setup-simple-ipsec-l2tp-vpn#26]
after i install this script when i try to start the service use sudo service ipsec-assist start

shows me :"ipsec-assist: unrecognized service"

**Comment by philplckthun** [comment]
We'll need an entire log of the installation process to debug this issue, as the script is as is thoroughly tested.

**Comment by tom95588** [comment]
Hi, thank you for fast response ,before install this script,  i have already installed PPTP on my server ,so is that cause this problem ?

**Comment by tom95588** [comment]
Hi, thank you for fast response ,before install this script,  i have already installed PPTP on my server ,so is that cause this problem ?

**Comment by philplckthun** [comment]
Could have caused a problem during the runtime of the script, but that's hard to say without a log
