### ISSUE TITLE
LibreSwan 3.13 warnings:     lex.yy.c:1925:12: warning: redundant redeclaration of ‘isatty’ [-Wredundant-decls]

### ISSUE THREAD

**Issue by kristianrl** [philplckthun/setup-simple-ipsec-l2tp-vpn#27]
I ran into this warning when installing the script on a brand-new Ubuntu 14.04 64-bit installation:

    Installing necessary dependencies...
    Extracting templates from packages: 100%
    Installing XL2TPD...
    Downloading LibreSwan's source...
    Compiling LibreSwan...
    /opt/src/libreswan-3.13/lib/libipsecconf/parser.y: warning: 2 shift/reduce conflicts [-Wconflicts-sr]
    /opt/src/libreswan-3.13/lib/libipsecconf/parser.y: warning: 4 reduce/reduce conflicts [-Wconflicts-rr]
    lex.yy.c:1925:12: warning: redundant redeclaration of ‘isatty’ [-Wredundant-decls]
     extern int isatty (int );
                ^
    In file included from /opt/src/libreswan-3.13/lib/libipsecconf/parser.l:30:0:
    /usr/include/unistd.h:779:12: note: previous declaration of ‘isatty’ was here
     extern int isatty (int __fd) __THROW;
                ^

Apart from the warning, the installation succeeded. So treat this as low-priority.

**Comment by philplckthun** [comment]
Those are normal code compilation warnings. It's safe to ignore them. :wink:
