### ISSUE TITLE
Can I use this script for linode vps？

### ISSUE THREAD

**Issue by bindiry** [philplckthun/setup-simple-ipsec-l2tp-vpn#28]
os: ubuntu 14.04 x64

**Comment by theroyalstudent** [comment]
Of course, why not? It should work flawlessly.

**Comment by philplckthun** [comment]
Give it a try and report back please, so we can add it to the list of tested OS and VPS combos ;)

**Comment by theroyalstudent** [comment]
Hmmm did it work?

**Comment by bindiry** [comment]
@theroyalstudent LOL, You are cunning. :)
I don't have to try.

**Comment by theroyalstudent** [comment]
You don't have to be such an asshole, don't you know that? Seriously.

**Comment by philplckthun** [comment]
@bindiry Please don't open issues if you're asking trivial questions. The title clearly states that it supports: Ubuntu, Arch Linux and Debian. Furthermore it says on what platforms it has been tested on.

If you're just lurking, then don't create useless issues. Especially don't be aggressive if someone just asks whether your things work out.

If you're using this project for free and request help, of course you gotta have the commitment to try and help as well.

And @theroyalstudent, language.
