### ISSUE TITLE
how to create a client script, thanks?

### ISSUE THREAD

**Issue by oldfeel** [philplckthun/setup-simple-ipsec-l2tp-vpn#6]

**Comment by philplckthun** [comment]
This wouldn't be as trivial; due to multiple, possible programs that can be utilised to access VPNs. It also varies extremely from device to device. I advise you to look up tutorials on how to set up your "IPSec L2TP client". :smiley:

**Comment by oldfeel** [comment]
好亲切的头像...我使用相同的配置,用这个http://freel2tpvpn.com/的免费服务器可以连接成功,但是用 amazon ec2 上用你的脚本配置的就连不上了,测试系统(都是64位):

服务器有
  - ubuntu 14.10
  - ubuntu 14.04

客户端有
  - mac os 10.10 系统自带的vpn连接
  - ubuntu 14.10 network-manager-l2tp-gnome
  - ubuntu 14.04 network-manager-l2tp-gnome
